export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS'
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL'
export const COMMENT_LIST_RESET = 'COMMENT_LIST_RESET'

export const COMMENT_ADD_REQUEST = "COMMENT_ADD_REQUEST"
export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS"
export const COMMENT_ADD_FAIL = "COMMENT_ADD_FAIL"